# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCircle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=30)),
                ('latCenter', models.FloatField()),
                ('longCenter', models.FloatField()),
                ('radius', models.FloatField()),
                ('countConnect', models.IntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomRect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=30)),
                ('countConnect', models.IntegerField()),
                ('lat1', models.FloatField()),
                ('long1', models.FloatField()),
                ('lat2', models.FloatField()),
                ('long2', models.FloatField()),
                ('lat3', models.FloatField()),
                ('long3', models.FloatField()),
                ('lat4', models.FloatField()),
                ('long4', models.FloatField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
